name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    steps: 
      - name: Portainer Service Webhook
        uses: newarifrh/portainer-service-webhook@v1
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
