services:
  server-php:
    image: server-php
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html

  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128m
    ports:
      - "3306:5432"
    environment:
      POSTGRES_USER: tlazzari
      POSTGRES_PASSWORD: Aix5Booyeepohfee
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
  
  pg-admin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: tlazzari@mail.it
      PGADMIN_DEFAULT_PASSWORD: pw
    volumes:
      - pgadmin-data:/var/lib/pgadmin:rw

volumes:
  pgdata:
  pgadmin-data: