services:
  database:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=rr
      - MARIADB_USER=u
      - MARIADB_PASSWORD=p
      - MARIADB_DATABASE=tecwebdb
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
 db-data: 