name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Portainer Service Webhook
        uses: newarifrh/portainer-service-webhook@v1
        with:
          webhook_url: ${{ secrets.webhook_url }}
